version: 2

models:
  - name: plan_detail
    description: Clean naming of plans for all products. Currently only graphpad exists.

sources:
  - name: graphpad_db
    schema: public
    tables:
      - name: subscriptions
        description: Contains all SnapGene registration codes
